### ISSUE TITLE
train.py no training sample

### ISSUE THREAD

**Issue by yhyu13** [yasharhezaveh/Ensai#6]
Hi,

I am facing an error generated by `train.py` after extracting SAURON_TEST to `data` folder and running `init.py`.

Here is the error message that asks for different training samples:
The first time:
```
INFO:tensorflow:Restoring parameters from data/trained_weights/model_9.ckpt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "train.py", line 45, in <module>
    read_data_batch( X , Y , MAG , num_training_samples , 'train' )
  File "get_data.py", line 240, in read_data_batch
    ARCS = np.array(Image.open(arc_filename),dtype='float32').reshape(numpix_side*numpix_side,)/65535.0
  File "/home/hangyu5/anaconda2/envs/py2dl/lib/python2.7/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/SAURON_TEST/train_0065979.png'

```
The second time:
```
IOError: [Errno 2] No such file or directory: 'data/SAURON_TEST/train_0006216.png'
```
The thired time:
```
IOError: [Errno 2] No such file or directory: 'data/SAURON_TEST/train_0043146.png'
```
It seems like SAURON_TEST doesn't include training samples, am I supposed to follow the README to entirely generate new training samples?

Thanks

**Comment by yemeen** [comment]
I had to generate my own set of training data using the Lensing_TrainingImage_Generator.m file which required access to Matlab. If you have access to Matlab, then the file containing all of the galaxy images to be lensed can be found here #4.
